# Site settings
title: Recovering melancholic
description: Chronicles of a recovering melancholic
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Comments (giscus - https://giscus.app)
giscus:
  repo: "recoveringmeloncholic/recoveringmeloncholic.github.io"
  repo_id: "R_kgDOLKuv0g"
  category: "Comments"
  category_id: "DIC_kwDOLKuv0s4DEARY"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
